---
title: "ByteNestDAO Strategic Pitch Deck"
author: "Jan Janssens"
date: "April 2025"
geometry: margin=1in
mainfont: DejaVu Sans
monofont: DejaVu Sans Mono
fontsize: 11pt
colorlinks: true
linkcolor: blue
urlcolor: blue
toc: true
---